import { expect, test } from "bun:test";
import { lstat, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { issueKey, createRun } from "../testing/session.ts";
import { execute } from "../../../packages/cli/runtime/execute.ts";
import { callTool, catalog } from "../../../packages/mcp/runtime/tools.ts";
import { fixture, uploaded, type Metadata } from "./testing/blob-fixture.ts";

test("scope escape exposes foreign bytes or lets a non-owner delete a nested key", async () => {
  const f = await fixture();
  try {
    expect((await f.put("../escape")).status).toBe(422);
    expect((await f.put("notes%2f..%2fescape")).status).toBe(422);
    expect((await f.put("notes%252fescape")).status).toBe(422);
    expect((await f.put("a/b/c/d/e")).status).toBe(422);
    const bytes = Buffer.from([0, 255, 128, 10]), blob = await uploaded(await f.put("notes/a.txt", bytes));
    const read = await f.get(blob.id); expect(read.status).toBe(200); expect(Buffer.from(await read.arrayBuffer())).toEqual(bytes);
    expect(read.headers.get("cache-control")).toBe("no-store"); expect(read.headers.get("content-disposition")).toBe("attachment");
    expect((await lstat(join(f.dataDir, "blobs", f.workspaceId))).mode & 0o777).toBe(0o700);
    expect((await lstat(join(f.dataDir, "blobs", f.workspaceId, blob.id))).mode & 0o777).toBe(0o600);
    expect((await f.put("notes/a.txt")).status).toBe(409);
    const principal = await (await f.json("/principals", { name: "Other" })).json() as { id: string };
    const otherKey = await issueKey(f.app, f.cookie, f.workspaceId, principal.id), otherRun = await createRun(f.app, otherKey, f.workspaceId);
    expect((await f.del(blob.id, { authorization: `Bearer ${otherKey}`, "x-backplane-run": otherRun })).status).toBe(403);
    expect((await f.get(blob.id, { authorization: `Bearer ${otherKey}` })).status).toBe(200);
    const foreign = await (await f.app.handle(new Request("http://localhost/api/v1/workspaces", { method: "POST", headers: f.userHeaders, body: '{"name":"Foreign"}' }))).json() as { id: string };
    expect((await f.app.handle(new Request(`http://localhost/api/v1/workspaces/${foreign.id}/blobs/${blob.id}`, { headers: f.userHeaders }))).status).toBe(404);
    expect((await f.app.handle(new Request(`http://localhost/api/v1/workspaces/${foreign.id}/blobs/${blob.id}`, { headers: f.headers }))).status).toBe(403);
    const linkId = crypto.randomUUID(); await symlink(join(f.dataDir, "blobs", f.workspaceId, blob.id), join(f.dataDir, "blobs", f.workspaceId, linkId));
    await expect(f.disk.open(f.workspaceId, linkId)).rejects.toThrow();
    const output = join(f.dataDir, "download"), env = { BP_URL: "http://localhost", BP_KEY: f.key, BP_WORKSPACE_ID: f.workspaceId, BP_RUN_ID: f.runId, XDG_STATE_HOME: f.dataDir };
    const transport = ((url, init) => f.app.handle(new Request(url, init))) as typeof fetch;
    let stderr = "";
    const io = { env, transport, stdin: async () => "", stdout: () => {}, stderr: (text: string) => { stderr += text; } };
    expect(await execute(["blobs", "get-blob", "--id", blob.id, "--out", output], io)).toBe(0); expect(stderr).toBe("");
    expect(await Bun.file(output).bytes()).toEqual(bytes);
    await writeFile(output, "keep");
    expect(await execute(["blobs", "get-blob", "--id", blob.id, "--out", output], io)).toBe(2);
    expect(await Bun.file(output).text()).toBe("keep");
    expect(await execute(["blobs", "get-blob", "--id", blob.id, "--out", output, "--force"], io)).toBe(0);
    expect(await Bun.file(output).bytes()).toEqual(bytes);
    const destinationLink = join(f.dataDir, "download-link"); await symlink(output, destinationLink);
    expect(await execute(["blobs", "get-blob", "--id", blob.id, "--out", destinationLink, "--force"], io)).toBe(2);
    expect(await Bun.file(output).bytes()).toEqual(bytes); expect((await lstat(destinationLink)).isSymbolicLink()).toBe(true);
    expect(await execute(["blobs", "put-blob", "--key", "cli/file.bin", "--file", output], io)).toBe(0);
    expect(await execute(["blobs", "put-blob", "--key", "cli/stdin.bin", "--file", "-"], { ...io, stdinBytes: async () => bytes })).toBe(0);
    const uploadTool = catalog.find((tool) => tool.name === "putBlob")!;
    const uploadResult = await callTool(uploadTool.command, { key: "mcp/file.bin", file: output }, { env, transport });
    expect(uploadResult.isError).toBe(false);
    const toolBlob = JSON.parse(uploadResult.content[0]!.text) as Metadata;
    expect(Buffer.from(await (await f.get(toolBlob.id)).arrayBuffer())).toEqual(bytes);
    const tool = catalog.find((tool) => tool.name === "getBlob")!;
    const result = await callTool(tool.command, { id: blob.id }, { env, transport });
    expect(result.isError).toBe(false); expect(JSON.parse(result.content[0]!.text)).toEqual({ encoding: "base64", content: bytes.toString("base64"), size: 4 });
  } finally { await f.close(); }
});
